apiVersion: v1
kind: Service
metadata:
  name: sd-automation-hub
  namespace: automation-hub
  labels:
    app.kubernetes.io/name: sd-automation-hub
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: sd-automation-hub
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
